{% set name = "qtsass" %}
{% set version = "0.4.0" %}
{% set hash = "8341c6d2690f75d651916dcaf96b4fa8c6dc54ef1d96bbc39958cbaa475fbf41" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  noarch: python
  entry_points:
    - qtsass = qtsass.cli:main

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - libsass >=0.22.0
    - watchdog

test:
  requires:
    - python {{ python_min }}
  imports:
    - qtsass

about:
  home: http://github.com/spyder-ide/qtsass
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Compile SCSS files to valid Qt stylesheets
  description: |
    Compile SCSS files to valid Qt stylesheets
  dev_url: http://github.com/spyder-ide/qtsass

extra:
  recipe-maintainers:
    - ccordoba12
    - dalthviz
