{% set name = "qtsass" %}
{% set version = "0.3.1" %}
{% set hash = "d60e2d78fa88437843bfa3fb2bcae4495baf0d366891e0a1ebca637192666306" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  noarch: python
  entry_points:
    - qtsass = qtsass.cli:main

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - libsass
    - watchdog

test:
  imports:
    - qtsass

about:
  home: http://github.com/spyder-ide/qtsass
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Compile SCSS files to valid Qt stylesheets
  description: |
    Compile SCSS files to valid Qt stylesheets
  dev_url: http://github.com/spyder-ide/qtsass

extra:
  recipe-maintainers:
    - ccordoba12
    - dalthviz
